# Generated by Django 2.2 on 2022-05-29 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blogpost',
            table='blog_post',
        ),
    ]
