# Generated by Django 2.2 on 2022-06-08 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blogpost_published_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_at', '-updated_at', '-created_at']},
        ),
    ]
