# Generated by Django 2.2 on 2022-06-13 07:47

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20220608_1737'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blogpost',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
